language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

before_install:
  # GolangCI-lint
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin vX.Y.Z
  - golangci-lint --version

install:
  - go mod tidy
  - go mod download

script:
  - golintci-lint run --enable-all ./...
  - go test ./...
